exports.up = function(knex) {
    return knex.schema.createTable('typo_key_count', (table) => {
        table.integer('user_id').notNullable();
        table.foreign('user_id').references('id').inTable('users').onDelete('CASCADE');

        table.integer('typo_a_key').defaultTo(0);
        table.integer('typo_b_key').defaultTo(0);
        table.integer('typo_c_key').defaultTo(0);
        table.integer('typo_d_key').defaultTo(0);
        table.integer('typo_e_key').defaultTo(0);
        table.integer('typo_f_key').defaultTo(0);
        table.integer('typo_g_key').defaultTo(0);
        table.integer('typo_h_key').defaultTo(0);
        table.integer('typo_i_key').defaultTo(0);
        table.integer('typo_j_key').defaultTo(0);
        table.integer('typo_k_key').defaultTo(0);
        table.integer('typo_l_key').defaultTo(0);
        table.integer('typo_m_key').defaultTo(0);
        table.integer('typo_n_key').defaultTo(0);
        table.integer('typo_o_key').defaultTo(0);
        table.integer('typo_p_key').defaultTo(0);
        table.integer('typo_q_key').defaultTo(0);
        table.integer('typo_r_key').defaultTo(0);
        table.integer('typo_s_key').defaultTo(0);
        table.integer('typo_t_key').defaultTo(0);
        table.integer('typo_u_key').defaultTo(0);
        table.integer('typo_v_key').defaultTo(0);
        table.integer('typo_w_key').defaultTo(0);
        table.integer('typo_x_key').defaultTo(0);
        table.integer('typo_y_key').defaultTo(0);
        table.integer('typo_z_key').defaultTo(0);
        table.integer('typo_A_key').defaultTo(0);
        table.integer('typo_B_key').defaultTo(0);
        table.integer('typo_C_key').defaultTo(0);
        table.integer('typo_D_key').defaultTo(0);
        table.integer('typo_E_key').defaultTo(0);
        table.integer('typo_F_key').defaultTo(0);
        table.integer('typo_G_key').defaultTo(0);
        table.integer('typo_H_key').defaultTo(0);
        table.integer('typo_I_key').defaultTo(0);
        table.integer('typo_J_key').defaultTo(0);
        table.integer('typo_K_key').defaultTo(0);
        table.integer('typo_L_key').defaultTo(0);
        table.integer('typo_M_key').defaultTo(0);
        table.integer('typo_N_key').defaultTo(0);
        table.integer('typo_O_key').defaultTo(0);
        table.integer('typo_P_key').defaultTo(0);
        table.integer('typo_Q_key').defaultTo(0);
        table.integer('typo_R_key').defaultTo(0);
        table.integer('typo_S_key').defaultTo(0);
        table.integer('typo_T_key').defaultTo(0);
        table.integer('typo_U_key').defaultTo(0);
        table.integer('typo_V_key').defaultTo(0);
        table.integer('typo_W_key').defaultTo(0);
        table.integer('typo_X_key').defaultTo(0);
        table.integer('typo_Y_key').defaultTo(0);
        table.integer('typo_Z_key').defaultTo(0);
    });
};

exports.down = function(knex) {
    return knex.schema.dropTable('typo_key_count');
};
