exports.up = function(knex) {
    return knex.schema.createTable('type_key_count', (table) => {
        table.integer('user_id').notNullable();
        table.foreign('user_id').references('id').inTable('users').onDelete('CASCADE');

        table.integer('a_key').defaultTo(0);
        table.integer('b_key').defaultTo(0);
        table.integer('c_key').defaultTo(0);
        table.integer('d_key').defaultTo(0);
        table.integer('e_key').defaultTo(0);
        table.integer('f_key').defaultTo(0);
        table.integer('g_key').defaultTo(0);
        table.integer('h_key').defaultTo(0);
        table.integer('i_key').defaultTo(0);
        table.integer('j_key').defaultTo(0);
        table.integer('k_key').defaultTo(0);
        table.integer('l_key').defaultTo(0);
        table.integer('m_key').defaultTo(0);
        table.integer('n_key').defaultTo(0);
        table.integer('o_key').defaultTo(0);
        table.integer('p_key').defaultTo(0);
        table.integer('q_key').defaultTo(0);
        table.integer('r_key').defaultTo(0);
        table.integer('s_key').defaultTo(0);
        table.integer('t_key').defaultTo(0);
        table.integer('u_key').defaultTo(0);
        table.integer('v_key').defaultTo(0);
        table.integer('w_key').defaultTo(0);
        table.integer('x_key').defaultTo(0);
        table.integer('y_key').defaultTo(0);
        table.integer('z_key').defaultTo(0);
        table.integer('A_key').defaultTo(0);
        table.integer('B_key').defaultTo(0);
        table.integer('C_key').defaultTo(0);
        table.integer('D_key').defaultTo(0);
        table.integer('E_key').defaultTo(0);
        table.integer('F_key').defaultTo(0);
        table.integer('G_key').defaultTo(0);
        table.integer('H_key').defaultTo(0);
        table.integer('I_key').defaultTo(0);
        table.integer('J_key').defaultTo(0);
        table.integer('K_key').defaultTo(0);
        table.integer('L_key').defaultTo(0);
        table.integer('M_key').defaultTo(0);
        table.integer('N_key').defaultTo(0);
        table.integer('O_key').defaultTo(0);
        table.integer('P_key').defaultTo(0);
        table.integer('Q_key').defaultTo(0);
        table.integer('R_key').defaultTo(0);
        table.integer('S_key').defaultTo(0);
        table.integer('T_key').defaultTo(0);
        table.integer('U_key').defaultTo(0);
        table.integer('V_key').defaultTo(0);
        table.integer('W_key').defaultTo(0);
        table.integer('X_key').defaultTo(0);
        table.integer('Y_key').defaultTo(0);
        table.integer('Z_key').defaultTo(0);
    });
};

exports.down = function(knex) {
    return knex.schema.dropTable('type_key_count');
};
